repos:
  - repo: local
    hooks:
      - id: ruff-format
        name: Ruff Formatter
        entry: uv run ruff format .
        language: python
        types: [python]
        require_serial: true
        files: /
        pass_filenames: false
      - id: ruff-lint-fix
        name: Ruff Lint (Apply Fixes)
        entry: uv run ruff check . --fix
        language: python
        types: [python]
        require_serial: true
        files: /
