fs = require 'fs'
{spawn} = require 'child_process'

# TODO: Determine a better convention

srcCoffeeDir         = 'coffeescripts/'
targetJsDir          = 'js/'

testSrcCoffeeDir     = 'test/'
testTargetJsDir      = 'test/'


build = (cb, src, target) ->
  ps = spawn "coffee", ['-c', '-o', target, src]
  ps.stdout.on 'data', (data) ->
    process.stdout.write data.toString()
  ps.stderr.on 'data', (data) ->
    # ?
    process.stderr.write data.toString()

  ps.on 'exit', (code) ->
    if code != 0
      process.stdout.write 'failed'
    else
      cb?()

buildSrc = (cb) ->
  build cb, srcCoffeeDir, targetJsDir

buildTests = (cb) ->
  build cb, testSrcCoffeeDir, testTargetJsDir

test = (cb) ->
  buildSrc ->
    buildTests ->
      ps = spawn "mocha"
      ps.stdout.on 'data', (data) ->
        process.stdout.write data.toString()
      ps.stderr.on 'data', (data) ->
        # ?
        process.stderr.write data.toString()

      ps.on 'exit', (code) ->
        if code != 0
          process.stdout.write 'failed'
        else
          cb?()

task 'build', 'compile code', buildSrc
task 'test', 'run tests', test
