# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-04-07 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0005_auto_20171225_1441"),
    ]

    operations = [
        migrations.AddField(
            model_name="cfauser",
            name="email_template",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="cfauser",
            name="send_email_template",
            field=models.BooleanField(default=False),
        ),
    ]
