# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-04-07 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20190407_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='cfauser',
            name='email_subject',
            field=models.TextField(blank=True),
        ),
    ]
