# Generated by Django 5.1.6 on 2025-09-05 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_alter_event_created_at_alter_event_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="cfauser",
            name="archived",
            field=models.BooleanField(default=False),
        ),
    ]
